#basic settings
server:
  servlet:
    context-path: /admin

#DB
spring.datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: 111111

#JPA
spring.jpa:
  generate-ddl: false # инициализация схемы (отключено)
  hibernate.ddl-auto: none # Нет инициализации схемы базы данных
#  show-sql: true

#User agent for Jsoup.connect
userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6

#List of sites
connection:
  sites:
#    - url: http://www.playback.ru
#      name: PlayBack.ru
    - url: https://nikoartgallery.com
      name: Креативное пространство и галерея Н.Б.Никогосяна
#    - url: https://www.svetlovka.ru
#      name: Светловка

